apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: solar-simulator
  namespace: monitoring
  labels:
    app: solar-simulator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: solar-simulator
  namespaceSelector:
    matchNames:
      - solar-monitoring
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
