apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solar-monitoring

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: solar-simulator
  managed-by: argocd

images:
  - name: solar-simulator
    newTag: latest
